### ISSUE TITLE
An author-mode assignment doesn't load after saving

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/dragoon-lms#27]
As Teacher:

1. Create a class
2. Create a model with a couple of complete nodes.
3. Create an assignment link for that model with mode "edit the model" (author mode assignment)

Then, as student:

1. Join the class
2. Open assignment link
3. Choose any folder (model loads successfully, you should see the nodes--worked with both private and custom-made folders)
4. Edit the model a little bit (move nodes around or add a new node)
5. Click Done
6. Go to models page and find the model (the model is successfully being added to the folder list)
7. Click on the model and select edit the model

At this point, the model you were editing should load; instead you get the new model created message and a completely blank model.

**Comment by riteshsamala** [comment]
Code open for review on bug_fixes branch of dragoon-lms

**Comment by jonwetzel** [comment]
Resolved by #28
