### ISSUE TITLE
Author mode problem link don't save properly in two cases

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/dragoon-lms#30]
- [x] Case 1

As teacher:

1. Create a class
2. Create a shared folder with student
3. Create an author mode assignment from a custom model (not in the shared folder)

As student:

1. Join class
2. Open assignment link 
3. Choose the shared folder
4. Edit model and click done
5. Go to shared folder, see model is there, try to edit it again  -- Instead of getting the edited version you get a new blank model (model was not found)

- [ ]  Case 2

As teacher:

1. Create a class
2. Create an author mode assignment from a model in the model library

As Student

1. Open assignment link
2. Choose any folder.  Problem fails to open.

**Comment by jonwetzel** [comment]
@riteshsamala Please look into this bug after you make the pull request for nodeeditor2.

**Comment by riteshsamala** [comment]
ok

**Comment by jonwetzel** [comment]
I'm downgrading this to P2 since Ignacio (SoS TA) told me they won't need this feature for their class yet.  We can complete it this sprint but wait on updating the live site till they find another bug we need to fix.

**Comment by jonwetzel** [comment]
The solution for Case 2 is partially coded up.  We will not allow users to create assignments in author mode from model library problems. (Author must copy it to their own custom model first.)

**Comment by jonwetzel** [comment]
The ban on creating assignments in author mode from model library problems was a temporary fix; now we can implement a full fix so authors can do that.

**Comment by jonwetzel** [comment]
Fix implemented by https://github.com/Dragoon-Lab/LMS/pull/10
