### ISSUE TITLE
A user should be able to leave a shared folder

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/dragoon-lms#32]
- [x] The delete dialog should include folders shared by others to the current user.  They can either be in the "shared" list, or in a new list called "Shared with me".  You can pick whichever method is simpler to implement.  If you add the new list, rename the old "shared" list "Shared by me"
- [x] When the user expands a folder which was shared by someone else, do not display the models inside (because the user cannot delete those anyway).  Instead, display the text "Only the owner can delete shared models.  Delete this folder if you want to stop sharing it."
- [x] When the user selects one or more folders which were shared by someone else and clicks delete, instead of deleting those folders, remove the current user from the set of users each folder is shared with.

**Comment by vanlehn** [comment]
Repurpose the Delete button, probably.

**Comment by jonwetzel** [comment]
@dharanisakary I'm done with the task description.  Please let me know if you have any questions.
