### ISSUE TITLE
Merge topomath-lms into dragoon-lms

### ISSUE THREAD

**Issue by jonwetzel** [Dragoon-Lab/dragoon-lms#41]

**Comment by sachingrover211** [comment]
Important references - https://www.drupal.org/docs/7/multisite-drupal/multi-site-in-subdirectories
https://www.drupal.org/node/823990

Steps to do this - 
* make sure to backup the databases for each website.
* download fresh copy of drupal and put it on public_html and public_html/devel - for devel version
* in sites folder create a folder called dragoon.asu.edu and topomath.asu.edu (for production versions) and dragoon.asu.edu.devel and topomath.asu.edu.devel (for devel versions)
* create appropriate databases and copy default.settings.php to each new folder created and rename it to settings.php. Copy the piece of code 
```php
$databases = array (
  'default' =>
  array (
    'default' =>
    array (
      'database' => 'testsite', 
      'username' => 'testuser', 
      'password' => 'password', 
      'host' => 'localhost', 
      'port' => '', 
      'driver' => 'mysql', 
      'prefix' => '', 
    ), 
  ), 
);
```
with appropriate changes for database name, usename and password.
* Call url/install.php to install a fresh copy of the website.
* Copy folders to appropriate modules and themes folders. The common code goes in default folder and site specific code goes in the site specific folder. By default modules and themes folders are not present in the sites folder. So create them as per the need.
* Update databases to use old databases and everything should be back to normal.

**Comment by sachingrover211** [comment]
@jonwetzel I need to know when to update the server because this will take sometime to setup atleast 4 hours if there are any hiccups. I have tested this on my local and after discussing with @riteshsamala I can divide the code as common and separate modules and themes. That way it will save our time when setting up the server. But I have been able to create dragoon.com and topomath.com on my local as well as tested the dragoon.com/devel for sub-directory based multi-site.

**Comment by sachingrover211** [comment]
@jonwetzel I will move this card to done as nothing has to be done on this and I need to move the thing to server now which I think I will do it after you come back.

**Comment by sachingrover211** [comment]
@jonwetzel @riteshsamala only problem here is we might need to setup the websites again. Because the old databases are not usable. We need to copy the users classes and assignments tables and merge them to our new database once we are done.
